#  docker-compose -f docker-compose.yml config check validate config
version: "3.1"
services:
  goapitest:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    image: "limweb/testapi"
    container_name: goapitest
    working_dir: /app
    restart: "always"
    ports:
      - "8080:8080"
    expose:
      - "8080" #ผ่าน reverproxy ไม่ต้องเปิด port
    labels:
      com.docker.compose.project: "servicname"
      virtual.host: "yourdomain.local.com"
      virtual.tls-email: your@email.com
      virtual.port: "8080"
    environment:
      VIRTUAL_HOST: "yourdomain.local.com"
      VIRTUAL_PORT: "8080"
      LETSENCRYPT_HOST: "yourdomain.local.com"
      LETSENCRYPT_EMAIL: your@email.com

networks:
  default:
    external:
      name: proxy-network


